### PR TITLE
build(cli): use `exports.types` package condition

### PR DESCRIPTION
**Pull request by tien**
The list of common known package conditions ban be found [here](https://nodejs.org/api/packages.html#community-conditions-definitions).

### CODE REVIEW

**Comment by tien** [comment]
Also, maybe the "exports.module" condition can be removed? I wasn't able to find any reference to it.

**Comment by voliva** [comment]
Is there a specific issue this is causing?

When we investigated it, it looks like typescript does get the types directly from the root's `type`.

Publint shows a warning for a different case, but even then when we looked it seemed fine since it also specifies that TS by default resolves to the neighbouring .d.ts of the JS file (which is the case).

**Comment by tien** [comment]
@voliva Oops, sorry, I meant to move the `types` from top-level into `exports` 😅. I don't think it right now has any real world different beside actually being part of the standard. Apparently it has some benefit for `nodenext`, `node16` & `bundler` resolution, but I haven't tested this out myself yet.

**Comment by voliva** [comment]
I would keep the root `types`, as it's on spec with the original types resolution, and removing this might actually break some tooling.

Based on [publint](https://publint.dev/polkadot-api@0.12.1), it's not giving any warning on that one. And also, it doesn't mention how the export's is missing a `types` entry either.

The only thing it's showing a warning is for a possible missing `types` under  `pkg.exports["."].import.types`, but that would be inside the `import` key. And following the explanation it says how this is not needed if you have neighbouring .d.ts next to the .js files (which we do).

I would personally agree to change this to solve an existing issue with a particular setup.

**Comment by tien** [comment]
Okay, that make sense, will close this PR for now.

**Pull request closed without merging**
