### PR TITLE
fix(chainspecs): Paseo ss58Format value

### LINKED ISSUE #833: change paseo ss58Format from 42 to 0
change paseo ss58Format from 42 to 0

### PR DESCRIPTION
**Pull request by josepot**
Closes #833

### CODE REVIEW

**Comment by carlosala** [comment]
Afaik paseo ss58 should be 42, at least we were doing that when I was in charge of the maintenance. We could reach out to ensure it is not a bug on their side

**Comment by josepot** [comment]
> Afaik paseo ss58 should be 42, at least we were doing that when I was in charge of the maintenance. We could reach out to ensure it is not a bug on their side

The on-chain constant is 0. Therefore, unless there is a runtime update that changes it, the chainspec should be consistent with the on-chain value. I.e: the on-chain constant is the actual SS58Format. I already opened [this issue](https://github.com/paseo-network/runtimes/issues/152) on their repo.

**Comment by carlosala** [comment]
Yes, exactly, we should match the constant. Let's discover in that issue what's going on. Thanks!

**Review by carlosala — APPROVED** [review]

**Comment by hbulgarini** [comment]
Hello ! i can bring some light here. @carlosala is right, we started with the `42` but after runtime upgrade 1.3.0 we decided to change it to `0` to make it closer to Polkadot.

Here is the GH issue where the fix was deployed: https://github.com/paseo-network/support/issues/103

**Pull request merged**
